id: P000413
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG2788
  title: བཀྲ་ཤིས་ལྷུན་པོའི་ཞལ་འདོན་ཆོས་སྤྱོད་རབ་གསལ།
  author: ''
  volumes:
    f3101926fc6e4c5687d5cf12d3df12a3:
      image_group_id: I1KG3143
      title: Volume 1 of bkra shis lhun po'i 'phags tshogs 'dus sde rin po che'i zhal
        'don chos spyod rab gsal
      volume_number: 1
      total_pages: 650
      base_file: v001.txt
ebook_metadata:
  title: བཀྲ་ཤིས་ལྷུན་པོའི་ཞལ་འདོན་ཆོས་སྤྱོད་རབ་གསལ།
  author: ''
  sku: P000413
  cover: cover.jpg
  layers:
  - pagination
